language: php

dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

install:
  - composer self-update
  - composer install

script:
  - make build

after_script:
  - vendor/bin/test-reporter
  - vendor/bin/php-cs-fixer fix -v --dry-run --stop-on-violation --using-cache=no src/
  - vendor/bin/phpstan analyze src/
